name: "@unis/transition CI/CD"

on:
  push:
    branches:
      - 'main'
    paths:
      - 'packages/unis-transition/**'

jobs:

  "publish":
    runs-on: ubuntu-latest
    if: ${{startsWith(github.event.head_commit.message, 'release(transition):')}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: "https://registry.npmjs.org"
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.9.0
      - run: |
          pnpm install
          cd packages/unis-core
          pnpm build
          cd ../packages/unis-transition
          pnpm build
          pnpm publish --no-git-checks --access public
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}